# Generated by Django 2.0 on 2019-05-11 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information',
            old_name='information_password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='information',
            old_name='information_name',
            new_name='username',
        ),
    ]
